### ISSUE TITLE
Icon request: terminal

### ISSUE THREAD

**Issue by thebaer** [DiemenDesign/LibreICONS#1]
Love the breadth of icons in this library -- especially for browsers and desktop OSes. Adding a terminal icon like this: http://fortawesome.github.io/Font-Awesome/icon/terminal/ would be awesome.

**Comment by ghost** [comment]
Thank you. I'm about to add a couple of others, will include a terminal icon as well.

**Comment by ghost** [comment]
Added a couple more Icons, including a Terminal Icon.
http://studiojunkyard.github.io/LibreICONS/icons.html
