### ISSUE TITLE
Wrong licence reference in CONTRIBUTING.md

### ISSUE THREAD

**Issue by pedrommalaquias** [DiemenDesign/LibreICONS#10]
https://github.com/DiemenDesign/LibreICONS/blob/master/CONTRIBUTING.md#license

'License
By contributing your code, you agree to license your contribution under the terms of the **GPLv3**:

https://github.com/DiemenDesign/LibreICONS/blob/master/LICENSE'

The project license is MIT, so this should be corrected. Thank you.

**Comment by DennisSuitters** [comment]
More than likely just a typo, will fix that. Thanks.
