### ISSUE TITLE
Elfinder theme styles

### ISSUE THREAD

**Issue by g-rodigy** [DiemenDesign/LibreICONS#11]
I used only files  for theme elFinder. When enabled quicklook, modal missing styles and when info panel on left sidebar too.

#### What Browser and Version
Chrome 84.0

#### What Operating System are you using?
Windows 10

#### Screenshot of Issue
![image](https://user-images.githubusercontent.com/30372087/88195807-ba12f800-cc40-11ea-8217-cf1bc3de16df.png)
![image](https://user-images.githubusercontent.com/30372087/88195822-bf704280-cc40-11ea-9ae2-ba34e7e90eda.png)

**Comment by g-rodigy** [comment]
Can you make new release, I uses this repo in my project with composer

**Comment by DennisSuitters** [comment]
I'll work on it over the next couple of days, as there are some additions, then I'll do a new release, it's probably about time anyway.
