### ISSUE TITLE
Possible to change icon color for summernote

### ISSUE THREAD

**Issue by 2braincells2go** [DiemenDesign/LibreICONS#6]
Everything working great but, wondering if simple way to change the svg icon color via css?

I am using a custom theme and happens to be black. The pencil and other icons are also black...

All other icons in summernote are now white but the libreicons are black making them invisble.

Thanks in advance.

Woody

**Comment by ghost** [comment]
Try using `fill:<color>;`, you can also use `fill:currentColor;` which will make the icon take on the color of it's parent element. I'm not sure if this works if the icon is pulled in via CSS as a background.

**Comment by 2braincells2go** [comment]
Thanks for input. I had already tried all the normal like `fill:white, fill:#ffffff and fill:currentcolor`, sorry, should have mentioned that.

Only thing I could come up with is `background-color: white;`

Not a perfect solution but prevents me from removing altogether.

Cheers

**Comment by ghost** [comment]
Yeah, I think that's a limitation of how SVG's work this way with CSS.
If the SVG were able to be inline, then it wouldn't matter. I haven't worked out a way to do so with Summernote, but in LibreCMS I have them injected into the page using PHP, which reads the SVG file into the document, which then allows changing the icons colours, and so on..
I'm wondering now, if there may be a function within Summernote that builds the toolbar, and if it can be overridden to change it's function to inject the SVG files, and in turn allows us to manipulate them further.
_goes off digging through the Summernote code_

**Comment by ghost** [comment]
Actually, if I can work that out, it will fix another issue I've been having with loading SVG through CSS. Sometimes the Icons don't appear in chrome in the toolbar.

**Comment by 2braincells2go** [comment]
Well, think you have done an excellent job and issues are very minor:)

I did notice that when using chrome, icons sometime fail to appear.  I have gotten so use to chrome quirks did not mention it.

For now using the `background-color: <color>;` works for me.

Thanks much.

**Comment by ghost** [comment]
Cheers, for the kind words.

I'll keep working on finding solutions though, as the Chrome bug annoys me at times, lol.

**Comment by 2braincells2go** [comment]
Have been scratching my head why chrome is so flaky with svg icons. Ran across this and it might help you:

https://bugs.chromium.org/p/chromium/issues/detail?id=580809

**Comment by ghost** [comment]
Looks like some sort of Cache issue from what I can tell. Though their test is loading the SVG through an element in the pages, we're loading the SVG via the background in CSS. Not sure if it's exactly the same, but seems to produce a similar issue.
